name: Generate Swift Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_swift:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone external repository
        run: |
          git clone --depth=1 https://github.com/bluesky-social/atproto.git
          mkdir -p ATProtoKit/Generator/lexicons
          mv atproto/lexicons/* ATProtoKit/Generator/lexicons/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ATProtoKit/Generator/requirements.txt

      - name: Generate Swift code
        run: |
          python ATProtoKit/Generator/Generator.py ATProtoKit/Generator/lexicons ATProtoKit/Generator/generated_swift

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update generated Swift code"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
